<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyManagement.Devices.Protocol\KeyManagement.Devices.Protocol.csproj" />
  </ItemGroup>

</Project>
