<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KeyManagement.Infrastructure\KeyManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\KeyManagement.Application\KeyManagement.Application.csproj" />
    <ProjectReference Include="..\..\src\KeyManagement.Domain\KeyManagement.Domain.csproj" />
  </ItemGroup>

</Project>
